# Site settings
title:                 Chris Arcand
description:           'Principal Engineer building <a href="https://www.terraform.io/" target="_blank">Terraform</a> at <a href="https://www.hashicorp.com/" target="_blank">HashiCorp</a> üë®‚Äçüíª Formerly: <a href="https://www.redhat.com" target="_blank">Red Hat</a>, <a href="https://www.sportsengine.com/" target="_blank">NBC SportsEngine</a>, <a href="http://ruby.mn/">RubyMN</a> organizer. Once played the clarinet for a living, now making a living to play hockey. I make pointless connections to Minnesota as a Minnesotan does.'
location:              St. Paul, MN
url:                   'https://chrisarcand.com'
google_analytics:      'UA-41741905-2'

author:
  name:                Chris Arcand
  email:               chris@chrisarcand.com
  # twitter_username:    chrisarcand  Bye bye birdie
  github_username:     chrisarcand
  linkedin_username:   chrisarcand
  mastodon_username:   chrisarcand
  mastodon_instance:   hachyderm.io
  bluesky_username:    chrisarcand.com

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

gist_js_warning: "**Oops! You have Javascript disabled.** I use GitHub Gists to show code on my blog, which regrettably requires JavaScript. I only apologize if you're using an RSS reader :( Please visit the page with Javascript enabled!"

# Build settings
destination:           _site
paginate:              6
permalink:             /:categories/:title/
markdown:              kramdown
highlighter:           rouge
timezone:              America/New_York

kramdown:
  syntax_highlighter:  rouge
  input:               GFM # Github Flavored Markdown
  hard_wrap:           false # do not replace newlines by <br>s

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - src
